name: Auto build image
on:
  issue_comment:
    types:
      - created
jobs:
  issue_comment:
    name: Auto build image
    if: startswith(github.event.comment.body, '/autobuild')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:

      - name: Auto build image
        id: autobuild
        run: |
          commentbody="${{github.event.comment.body}}"
          commentbody=$(echo $commentbody | sed "s/\/imagebuild//g")
          sudo git clone https://github.com/Stevent-fei/blog.git && cd blog
          sudo touch autobuild.log && sudo chmod 666 autobuild.log && sudo bash auto-main-arm.sh --username="${{secrets.REGISTRY_USERNAME}}" --password="${{secrets.REGISTRY_PASSWORD}}" $commentbody > autobuild.log && cat autobuild.log
          echo "::set-output name=info::$(grep 'cri:' autobuild.log))"

      - name: Success Commit
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ steps.autobuild.outputs.info }}