# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: Auto build image
on: #[push, pull_request]
  issue_comment:
    types:
      - created
jobs:
  issue_comment:
    name: Auto build image
    if: ${{ github.event.comment.body == '/make build v1.20.14 ADM64' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:

      - name: Check outputs
        run: |
          wget http://sealer.oss-cn-beijing.aliyuncs.com/k8s/rootfs.tar.gz
          tar -xvf rootfs.tar.gz
          wget https://dl.k8s.io/v1.20.14/kubernetes-server-linux-amd64.tar.gz
          tar -xvf kubernetes-server-linux-amd64.tar.gz
          sudo cp ./kubernetes/server/bin/kubectl ./rootfs2/bin/
          sudo cp ./kubernetes/server/bin/kubeadm ./rootfs2/bin/
          sudo cp ./kubernetes/server/bin/kubelet ./rootfs2/bin/
          cd ./rootfs2
          echo k8s.gcr.io/kube-apiserver:v1.20.14 \
          k8s.gcr.io/kube-controller-manager:v1.20.14 \
          k8s.gcr.io/kube-scheduler:v1.20.14 \
          k8s.gcr.io/kube-proxy:v1.20.14 \
          k8s.gcr.io/pause:3.2 \
          k8s.gcr.io/etcd:3.4.13-0 \
          k8s.gcr.io/coredns:1.7.0 >> imageList
          ls -R
          wget http://sealer.oss-cn-beijing.aliyuncs.com/sealers/sealer-v0.6.1-linux-amd64.tar.gz
          sudo tar -xvf sealer-v0.6.1-linux-amd64.tar.gz -C /usr/bin
          sudo sealer build -f Kubefile -m lite -t kubernetes:v1.20.14 .
          sudo sealer push kubernetes:v1.20.14
      - name: Auto build image
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            kubernetes:v1.20.14
